language: ruby
rvm:
- 2.1.2
env:
- DB=postgres
before_script:
- psql -c 'create database shindo_test;' -U postgres
bundler_args: "--binstubs=./bundler_stubs"
deploy:
  provider: heroku
  api_key:
    secure: dldCHuPaDnPtHviLszZ2ANU/n5D42gS0oQYxfYLKGBdrs9Is5cEvw8xTBvBJnJJZkq0uIgoK4jPyFkTTtDNsPLo99IrtapUDv96RjPTNQjcz0Jin4/tscMqWitQugL5vyTi2YnG+SRrtnhYx/1kSX4OdpmE4hFW7lKIbgRCZGCw=
  app: TaoZenAcademy
  on:
    repo: sprestage/TaoZenAcademy
